# 每日自动修改 Zepp 步数（cron 0 4 UTC = 北京时间 12:00）
name: 自动任务-修改Zepp当天运动数据

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: '检出仓库代码'
        uses: actions/checkout@v6
      - name: '设置 Python 环境'
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.0'
      - name: '安装依赖项'
        run: pip install requests==2.26.0
      - name: '运行主程序'
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ./main.py
